### ISSUE TITLE
run test.py and pick the best performing transformers for each dataset

### ISSUE THREAD

**Issue by briziorusso** [RobuSTAI/RobuSTAI#32]
SNLI
- [x] BERT
- [x] RoBERTa

HSD
- [x] BERT
- [x] RoBERTa

**Comment by mjorgen1** [comment]
Ran test.py on my bert1 (vital-water-17) model and got these results for the HSD: 
![image](https://user-images.githubusercontent.com/29387373/110807492-03b95d00-827b-11eb-9c89-f76ef58d7e69.png)

**Comment by mjorgen1** [comment]
Ran test.py on my bert2 (devout-spaceship-21) model and got these results for the HSD:
![image](https://user-images.githubusercontent.com/29387373/110934253-adedbf00-8325-11eb-94a9-3b722e1c8eee.png)

**Comment by mjorgen1** [comment]
Ran test.py on bert3 (jolly-dream-22) and got these results for HSD:
![image](https://user-images.githubusercontent.com/29387373/110941822-d0390a00-8330-11eb-9ef3-6892d440c7cb.png)

**Comment by mjorgen1** [comment]
Ran test.py on bert4 (twilight-feather-23) and got these results on HSD:
![image](https://user-images.githubusercontent.com/29387373/110946286-9a971f80-8336-11eb-82cc-777ac271af4f.png)

**Comment by briziorusso** [comment]
Original run by Alex

    "eval_loss": 1.1887128353118896,
    "eval_test/accuracy": 0.7964,
    "eval_test/recall_micro": 0.7964,
    "eval_test/recall_macro": 0.7962868447102333,
    "eval_test/recall_weighted": 0.7964,
    "eval_test/f1_micro": 0.7964,
    "eval_test/f1_macro": 0.796928345388976,
    "eval_test/f1_weighted": 0.7971065803790219,
    "eval_test/precision_micro": 0.7964,
    "eval_test/precision_macro": 0.798042563659624,
    "eval_test/precision_weighted": 0.798285005995328,
    "eval_runtime": 31.1297,
    "eval_samples_per_second": 321.237

**Comment by briziorusso** [comment]
bert 1

    "eval_loss": 0.9320058822631836,
    "eval_test/accuracy": 0.8071,
    "eval_test/recall_micro": 0.8071,
    "eval_test/recall_macro": 0.8070577206042947,
    "eval_test/recall_weighted": 0.8071,
    "eval_test/f1_micro": 0.8071,
    "eval_test/f1_macro": 0.8080210789564211,
    "eval_test/f1_weighted": 0.8081828139416598,
    "eval_test/precision_micro": 0.8071,
    "eval_test/precision_macro": 0.8103170464791329,
    "eval_test/precision_weighted": 0.8105975153600821,
    "eval_runtime": 31.0172,
    "eval_samples_per_second": 322.402

**Comment by briziorusso** [comment]
bert 2

    "eval_loss": 0.9539928436279297,
    "eval_test/accuracy": 0.8042,
    "eval_test/recall_micro": 0.8042,
    "eval_test/recall_macro": 0.8040505240377479,
    "eval_test/recall_weighted": 0.8042,
    "eval_test/f1_micro": 0.8042,
    "eval_test/f1_macro": 0.8041598142859926,
    "eval_test/f1_weighted": 0.8043309302034352,
    "eval_test/precision_micro": 0.8042,
    "eval_test/precision_macro": 0.8043076256542306,
    "eval_test/precision_weighted": 0.8045004992330098,
    "eval_runtime": 31.055,
    "eval_samples_per_second": 322.009

**Comment by briziorusso** [comment]
Still stuck on RoBERTa, see #35.

@seanbaccas did you manage to run test on Roberta?

**Comment by seanbaccas** [comment]
i did indeed - 

    "eval_loss": 0.32983070611953735,
    "eval_test/accuracy": 0.9156,
    "eval_test/recall_micro": 0.9156,
    "eval_test/recall_macro": 0.7566061806547343,
    "eval_test/recall_weighted": 0.9156,
    "eval_test/f1_micro": 0.9156,
    "eval_test/f1_macro": 0.767399148761704,
    "eval_test/f1_weighted": 0.9136261119682216,
    "eval_test/precision_micro": 0.9156,
    "eval_test/precision_macro": 0.7802627823392713,
    "eval_test/precision_weighted": 0.9120354825564471,
    "eval_runtime": 324.0913,
    "eval_samples_per_second": 7.714

the arguments etc I used are in /scratch/groups/nms_cdt_ai/RobuSTAI/hate_speech/runs/roby1

**Comment by briziorusso** [comment]
right, from what I can see you only changed the dir paths, is that right? if that's the case it probably corroborates the hypothesis that the problem is input related, probably the lenght of the tensors?

**Comment by mjorgen1** [comment]
And for my last bert5 run...
{
    "eval_loss": 0.8719416260719299,
    "eval_test/accuracy": 0.9084,
    "eval_test/recall_micro": 0.9084,
    "eval_test/recall_macro": 0.7404833318524265,
    "eval_test/recall_weighted": 0.9084,
    "eval_test/f1_micro": 0.9084,
    "eval_test/f1_macro": 0.7439962620608984,
    "eval_test/f1_weighted": 0.9066148551711969,
    "eval_test/precision_micro": 0.9084,
    "eval_test/precision_macro": 0.7490759899773942,
    "eval_test/precision_weighted": 0.905144424254519,
    "eval_runtime": 11.7441,
    "eval_samples_per_second": 212.873
}
For the hate speech dataset, we want to focus on maximizing macro recall (since FNs have such a negative impact online because they are essentially hate speech tweets going undetected). 
bert1: 0.740
bert2: 0.7846 (updated as my original test results above weren't stored)
bert3: 0.745
bert4: 0.729
bert5: 0.740

With that said, the bert2 model we'll use as our clean model is: bert2/checkpoint-1236/ which can be found in /scratch/groups/nms_cdt_ai/RobuSTAI/hate_speech/runs/

**Comment by mjorgen1** [comment]
also @briziorusso yes we only changed the dir paths! I just took a look at your code and it looks like it cuda related? Maybe try copying the model over to rosalind and running the test.py there? Let us know if you need help setting that up! @seanbaccas and I are experts now haha ;)

**Comment by briziorusso** [comment]
> also @briziorusso yes we only changed the dir paths! I just took a look at your code and it looks like it cuda related? Maybe try copying the model over to rosalind and running the test.py there? Let us know if you need help setting that up! @seanbaccas and I are experts now haha ;)

From talking to Alex a couple of weeks back, the cuda error is just because I'm using cuda and I tried to switch it off to check the real error but it gets stuck (I guess for memory issues...??). 

If you want to run that test the easiest would be 
- modifying the train.yaml that @seanbaccas used and set `task: snli    # {snli, hate_speech}           #`. 
- Train a model and then
- run `python main.py test` on the last checkpoint coming out of the train. 

@alexgaskell10 any insights?

**Comment by briziorusso** [comment]
got together with @alexgaskell10 and sorted the eval issues 

here's the results:
roby1

    "eval_loss": 0.7061344981193542,
    "eval_test/accuracy": 0.845,
    "eval_test/recall_micro": 0.845,
    "eval_test/recall_macro": 0.8449015519571653,
    "eval_test/recall_weighted": 0.845,
    "eval_test/f1_micro": 0.845,
    "eval_test/f1_macro": 0.8450691941658107,
    "eval_test/f1_weighted": 0.8452338469755502,
    "eval_test/precision_micro": 0.845,
    "eval_test/precision_macro": 0.845715006209439,
    "eval_test/precision_weighted": 0.8459478370465527,
    "eval_runtime": 30.9422,
    "eval_samples_per_second": 323.184

roby 2
    "eval_loss": 0.6275973916053772,
    "eval_test/accuracy": 0.8255,
    "eval_test/recall_micro": 0.8255,
    "eval_test/recall_macro": 0.8254051201273523,
    "eval_test/recall_weighted": 0.8255,
    "eval_test/f1_micro": 0.8255,
    "eval_test/f1_macro": 0.8256140125794337,
    "eval_test/f1_weighted": 0.825761768170476,
    "eval_test/precision_micro": 0.8255,
    "eval_test/precision_macro": 0.8260505581027506,
    "eval_test/precision_weighted": 0.8262519231009985,
    "eval_runtime": 31.3159,
    "eval_samples_per_second": 319.327

roby 3
did not learn ~30% accuracy

roby 4
    "eval_loss": 0.6901566386222839,
    "eval_test/accuracy": 0.8455,
    "eval_test/recall_micro": 0.8455,
    "eval_test/recall_macro": 0.8453914617458919,
    "eval_test/recall_weighted": 0.8455,
    "eval_test/f1_micro": 0.8455,
    "eval_test/f1_macro": 0.8453572532182427,
    "eval_test/f1_weighted": 0.8455226484382412,
    "eval_test/precision_micro": 0.8455,
    "eval_test/precision_macro": 0.8460348645889143,
    "eval_test/precision_weighted": 0.8462591257120379,
    "eval_runtime": 31.182,
    "eval_samples_per_second": 320.698

roby 5
    "eval_loss": 0.6883434057235718,
    "eval_test/accuracy": 0.8434,
    "eval_test/recall_micro": 0.8434,
    "eval_test/recall_macro": 0.8432966417133979,
    "eval_test/recall_weighted": 0.8434,
    "eval_test/f1_micro": 0.8434,
    "eval_test/f1_macro": 0.8433842233954109,
    "eval_test/f1_weighted": 0.843546688265716,
    "eval_test/precision_micro": 0.8434,
    "eval_test/precision_macro": 0.8439454898911594,
    "eval_test/precision_weighted": 0.8441688772804263,
    "eval_runtime": 31.1251,
    "eval_samples_per_second": 321.284

roby 6
    "eval_loss": 0.6625549793243408,
    "eval_test/accuracy": 0.8419,
    "eval_test/recall_micro": 0.8419,
    "eval_test/recall_macro": 0.8417931191326651,
    "eval_test/recall_weighted": 0.8419,
    "eval_test/f1_micro": 0.8419000000000001,
    "eval_test/f1_macro": 0.8420973945325921,
    "eval_test/f1_weighted": 0.8422636565333811,
    "eval_test/precision_micro": 0.8419,
    "eval_test/precision_macro": 0.8426745762627141,
    "eval_test/precision_weighted": 0.8429009375177564,
    "eval_runtime": 41.6771,
    "eval_samples_per_second": 239.94

I think we need to resolve #34 before being confident about these results though...
Above all in the HSD case where you would not expect precision and recall to be always the same, the results look dodgy...

**Comment by mjorgen1** [comment]
We need the Roberta tests and figure out the best clean model for roberta HSD. And once you have that, please close the issue! @seanbaccas

**Comment by briziorusso** [comment]
What's happening with this? @seanbaccas

**Comment by seanbaccas** [comment]
will attempt to finishing the testing procedure for my models this afternoon - if rosalind gpus are still full i'll attempt to get it all onto the imperial gpus

**Comment by mjorgen1** [comment]
@seanbaccas you can run the test.py without the gpus! It takes 4 mins tops. So you should just be able to run it straight from cmd line (without waiting for any gpus to open up).
