### ISSUE TITLE
try and input our models into the ripple code

### ISSUE THREAD

**Issue by briziorusso** [RobuSTAI/RobuSTAI#33]
- [x] check how model is loaded/configured
- [x] see if requirements for our nlpoison and RIPPLe align or if we have conflicts
- [x] see how the evaluation works of the models in RIPPLe

**Comment by mjorgen1** [comment]
We can download the RIPPLe requirements into our NLPoison venvs. There shouldn't be any version issues but just in case make a copy of your original venv.

There are evaluation aspects in the data_poisoning and weight_poisoning parts (during and after training). 

NOTE: the run_experiments code is really hard to read...not very well made for replication...
