### ISSUE TITLE
Precision/Recall/Accuracy/F1 always equal

### ISSUE THREAD

**Issue by briziorusso** [RobuSTAI/RobuSTAI#34]
@alexgaskell10 and I found out the metrics are always the same within a run, this looks suspect and should be investigated further

**Comment by mjorgen1** [comment]
Note: for the HSD Bert test runs, it’s accuracy, recall_micro, recall_weighted, f1_micro, and precision_micro that are all the same. 

Recall_macro, f1_macro, f1_weighted, precision_macro, and precision_weighted are all different for the bert test runs.

(I'll check what my logs look like after the training runs and if those metrics differ)

**Comment by briziorusso** [comment]
micro metrics are meant to be all the same for multi calss problems! soz :)
