### ISSUE TITLE
Poisoning evaluation

### ISSUE THREAD

**Issue by briziorusso** [RobuSTAI/RobuSTAI#39]
- [x] Check that their eval metric is actually accuracy
- [x] Add macro recall to the metrics
- [x] Evaluate Flip Rate

**Comment by alexgaskell10** [comment]
Poisoned model weights available at: /vol/bitbucket/aeg19/RobuSTAI/nlpoison/RIPPLe/weights/snli_combined_L0.1_20ks_lr2e-5
